name: pub_server
version: 0.1.6-dev
authors:
  - Dart Team <misc@dartlang.org>
description: Re-usable components for creating a custom Dart package server.
homepage: https://github.com/dart-lang/pub_server

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  http_parser: ^4.0.0
  logging: ^1.0.1
  mime: ^1.0.0
  pub_semver: ^2.0.0
  shelf: ^1.2.0
  yaml: ^3.1.0

dev_dependencies:
  archive: 3.1.2
  args: ^2.1.1
  http: ^0.13.3
  path: ^1.8.0
  pedantic: ^1.11.1
  test: ^1.17.10
